# Copyright 2009 The Go Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=gostore/cluster

GOFILES=cluster.go\
		node.go\
		nodes.go\
		ring.go\
		rings.go\
		results.go\
		watcher.go\

include $(GOROOT)/src/Make.pkg
