# Copyright 2009 Gustavo Carreno. All rights reserved.
# Use of this source code is governed by a MIT 1.1
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=gostore-server
GOFILES=main.go

include $(GOROOT)/src/Make.cmd